#!/usr/bin/env bash
# Download prebuilt Sherpa-ONNX shared libraries for Linux x64.
# Required to link the `stt` / `tts` / `local-ai` Cargo features.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/native/sherpa-onnx"
VERSION="${SHERPA_ONNX_VERSION:-v1.13.0}"
ARCHIVE="sherpa-onnx-${VERSION}-linux-x64-shared-lib.tar.bz2"
URL="https://github.com/k2-fsa/sherpa-onnx/releases/download/${VERSION}/${ARCHIVE}"

mkdir -p "$DEST"
cd "$DEST"

write_cargo_config() {
  local CONFIG="$ROOT/src-tauri/.cargo/config.toml"
  mkdir -p "$(dirname "$CONFIG")"
  cat > "$CONFIG" <<EOF
# Auto-generated by scripts/setup-sherpa-onnx.sh — do not commit machine-specific paths.
[env]
SHERPA_ONNX_LIB_DIR = "$DEST/lib"
EOF
  echo "Wrote $CONFIG"
}

if [[ -f lib/libsherpa-onnx-c-api.so && -f lib/libonnxruntime.so ]]; then
  echo "Sherpa-ONNX libs already present in $DEST/lib"
  write_cargo_config
  exit 0
fi

echo "Downloading $URL ..."
wget -q --show-progress -O "$ARCHIVE" "$URL"
tar -xjf "$ARCHIVE"
rm -rf lib
mv "sherpa-onnx-${VERSION}-linux-x64-shared-lib/lib" lib
rm -rf "sherpa-onnx-${VERSION}-linux-x64-shared-lib" "$ARCHIVE"

echo "Installed:"
ls -la lib/*.so
write_cargo_config
