/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CashflowRouteImport } from './routes/cashflow'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFinanceProxyRouteImport } from './routes/api/finance-proxy'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CashflowRoute = CashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceProxyRoute = ApiFinanceProxyRouteImport.update({
  id: '/api/finance-proxy',
  path: '/api/finance-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cashflow': typeof CashflowRoute
  '/dashboard': typeof DashboardRoute
  '/holdings': typeof HoldingsRoute
  '/performance': typeof PerformanceRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/api/finance-proxy': typeof ApiFinanceProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cashflow': typeof CashflowRoute
  '/dashboard': typeof DashboardRoute
  '/holdings': typeof HoldingsRoute
  '/performance': typeof PerformanceRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/api/finance-proxy': typeof ApiFinanceProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cashflow': typeof CashflowRoute
  '/dashboard': typeof DashboardRoute
  '/holdings': typeof HoldingsRoute
  '/performance': typeof PerformanceRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/api/finance-proxy': typeof ApiFinanceProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cashflow'
    | '/dashboard'
    | '/holdings'
    | '/performance'
    | '/planning'
    | '/settings'
    | '/api/finance-proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cashflow'
    | '/dashboard'
    | '/holdings'
    | '/performance'
    | '/planning'
    | '/settings'
    | '/api/finance-proxy'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cashflow'
    | '/dashboard'
    | '/holdings'
    | '/performance'
    | '/planning'
    | '/settings'
    | '/api/finance-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CashflowRoute: typeof CashflowRoute
  DashboardRoute: typeof DashboardRoute
  HoldingsRoute: typeof HoldingsRoute
  PerformanceRoute: typeof PerformanceRoute
  PlanningRoute: typeof PlanningRoute
  SettingsRoute: typeof SettingsRoute
  ApiFinanceProxyRoute: typeof ApiFinanceProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashflow': {
      id: '/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof CashflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance-proxy': {
      id: '/api/finance-proxy'
      path: '/api/finance-proxy'
      fullPath: '/api/finance-proxy'
      preLoaderRoute: typeof ApiFinanceProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CashflowRoute: CashflowRoute,
  DashboardRoute: DashboardRoute,
  HoldingsRoute: HoldingsRoute,
  PerformanceRoute: PerformanceRoute,
  PlanningRoute: PlanningRoute,
  SettingsRoute: SettingsRoute,
  ApiFinanceProxyRoute: ApiFinanceProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
